import chai = require('chai')
import chaiString = require('chai-string')
import chaiSubset = require('chai-subset')
import sinon = require('sinon')
import sinonChai = require('sinon-chai')
import chaiAsPromised = require('chai-as-promised')
import chaiShallowDeepEqual = require('chai-shallow-deep-equal')

chai.should()
chai.use(chaiString)
chai.use(chaiSubset)
chai.use(sinonChai)
chai.use(chaiAsPromised)
chai.use(chaiShallowDeepEqual)
